# Etapa 1: build
FROM node:22-slim AS builder

WORKDIR /app
COPY . .

RUN npm install && npm run build

# Etapa 2: nginx
FROM nginx:latest

# Remove o default do nginx
RUN rm -rf /usr/share/nginx/html/*

# Copia os arquivos do build
COPY --from=builder /app/dist /usr/share/nginx/html

# Copia a config customizada do nginx
COPY nginx/prod.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]