version: '3.8'

services:
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: nginx
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - backend_network
      - frontend_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: [ "gunicorn", "--bind", "0.0.0.0:8000", "mini_twitter.wsgi:application" ]
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    networks:
      - backend_network
      - frontend_network

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
    expose:
      - "5432"

  redis:
    image: redis:alpine
    networks:
      - backend_network
    expose:
      - "6379"

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: [ "celery", "-A", "mini_twitter", "worker", "--loglevel=info" ]
    depends_on:
      - redis
      - db
    networks:
      - backend_network

volumes:
  postgres_data:
  frontend_build:


networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
