version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/static
      - ./backend/media:/media
    depends_on:
      - backend
    networks:
      - backend_network
      - frontend_network
  backend:
    build: ./backend
    command: [ "gunicorn", "--bind", "0.0.0.0:8000", "mini_twitter.wsgi:application" ]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./backend/.env
    networks:
      - backend_network
      - frontend_network

  # Frontend (React)
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000/api
    networks:
      - frontend_network

  # Banco de Dados (PostgreSQL)
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
    expose:
      - "5432"

  redis:
    image: redis:alpine
    networks:
      - backend_network
    expose:
      - "6379"

  # Celery (worker)
  celery:
    build: ./backend
    command: [ "celery", "-A", "mini_twitter", "worker", "--loglevel=info" ]
    depends_on:
      - redis
      - db
    networks:
      - backend_network

volumes:
  postgres_data:


networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
