# backend/Dockerfile.prod
FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
	PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
	gcc \
	libpq-dev \
	netcat-openbsd \
	&& rm -rf /var/lib/apt/lists/*

RUN adduser --disabled-password appuser

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . .

# Dá permissão de escrita antes de virar o appuser
RUN mkdir -p /app/static /app/media && \
	chown -R appuser:appuser /app

USER appuser

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "mini_twitter.wsgi:application"]
