# Etapa 1: build
FROM python:3.13-slim AS builder


RUN apt-get update && apt-get install -y \
	build-essential \
	libpq-dev \
	&& rm -rf /var/lib/apt/lists/*


RUN adduser --uid 1000 --disabled-password --gecos "" appuser
USER appuser
WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --user -r requirements.txt

# Etapa 2: runtime
FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY --from=builder /home/appuser/.local /root/.local
ENV PATH=/root/.local/bin:$PATH

COPY . .

#RUN python manage.py collectstatic --noinput

CMD gunicorn core.wsgi:application \
	--bind 0.0.0.0:8000 \
	--workers 3 \
	--timeout 120
