version: "3.9"

services:
  backend:
    build: ./backend
    command: [ "gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application" ]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - backend_network

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend_network

  celery:
    build: ./backend
    command: celery -A mini_twitter worker --loglevel=inf
    env_file:
      - .env
    depends_on:
      - redis
      - web
    restart: unless-stopped
    networks:
      - backend_network

volumes:
  postgres_data:


networks:
  backend_network:
    driver: bridge
